repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-toml
    -   id: check-json
    -   id: mixed-line-ending
        args: ['--fix=lf']

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3.11

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]
        args: [--strict]

-   repo: https://github.com/pycqa/pylint
    rev: v2.17.4
    hooks:
    -   id: pylint
        args:
        - --max-line-length=88
        - --ignore-imports=yes
        - --disable=all
        - --enable=E,F,W  # Erros, Falhas e Warnings

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v3.2.2
    hooks:
    -   id: commitizen
        stages: [commit-msg]

-   repo: local
    hooks:
    -   id: check-duplicate-imports
        name: Check for duplicate imports
        entry: python script/check_imports.py
        language: python
        types: [python]
        pass_filenames: false
